trustpoint/pki/initializer/issuing_ca/file_import.py
trustpoint/pki/serializer/certificate.py
trustpoint/pki/serializer/credential.py
trustpoint/pki/serializer/key.py

Credential serializer, added zip and tar.gz serialization
Methods added to CredentialSerializer class to support zip and tar.gz files containing PEM files.
The private key can either be stored as PKCS#1 or PKCS#8 (default).
Methods added:
get_as_separate_pem_files(self, password: None | bytes = None, pkcs1: bool = False) -> tuple[bytes, bytes, bytes]
as_pem_zip(self, password: None | bytes = None, pkcs1: bool = False) -> bytes
as_pem_tar_gz(self, password: None | bytes = None, pkcs1: bool = False) -> bytes
**Legal**

Credential serializer, added zip and tar.gz serialization

---

trustpoint/pki/serializer/__init__.py
trustpoint/pki/serializer/base.py
trustpoint/pki/serializer/certificate.py
trustpoint/pki/serializer/credential.py
trustpoint/pki/serializer/key.py

Serializer package now complies to ruff
**Notes** 
Two slight changes to the ZIP and TAR.GZ methods of the CredentialSerializer.
Use the internal enum class PrivateKeyFormat to specify the format on call.
The default is the more secure PKCS#8 format, if not give.
**Legal**

Serializers - Ruff compliance

---

trustpoint/devices/tables.py
trustpoint/pki/initializer/issuing_ca/file_import.py
trustpoint/pki/pki/request/handler/rest.py

- PKCS12 PKI request uses serializer (reducing duplication)
- Fix CA from file initialization byte-to-string conversion
- do not fail hard on table rendering for unknown onboarding protocol
**Legal**

Pki request pkcs12 serializer

---

trustpoint/onboarding/templates/onboarding/manual/browser-download.html
trustpoint/onboarding/templates/onboarding/manual/download.html

PEM button was not yet added for manual onboarding, thus only PKCS12 download was possible despite the API already supporting manual PEM download.
**Legal**

Add PEM download to manual onboarding

---

trustpoint/pki/templates/pki/certificates/certificates.html
trustpoint/pki/templates/pki/truststores/truststores.html
trustpoint/pki/urls/pki.py

Related to #92
Fixes download of Trust Stores and Certificates using "Download selected" if only one has been selected.
Removes `/multiple` from `MultipleDownloadView` view regex. Due to the order, this regex still only matches if multiple certs/trust stores are requested.  Single selections will instead be matched by the following regex which will use the regular single download view.
**Notes** 
Please test a few downloads to see if the correct certificates are downloaded using the correct file types.
**Legal**

Fixed download selected certs with 1 selected (fixes #92)

---

trustpoint/discovery/mdns.py
trustpoint/pki/management/commands/create_tls_certs.py
trustpoint/trustpoint/settings.py

Related to #114 
Added config variables for the mDNS service broadcast IP and port to django settings.py.
If possible, we'd want to pass a default from Apache in a production enviroment.
Still, it needs to be added to SysConf Network settings for 1.0.0 as even Apache is not aware of the final Trustpoint address due to factors like which interface is used, NATs, ...
**Notes** 
These are the changes required on the Trustpoint-side to make Client and Zero-Touch Demo onboarding work regardless of IP and port. For the corresponding PR to the client, see https://github.com/TrustPoint-Project/trustpoint-client/pull/8
**Legal**

Configurable mDNS host in Django settings

---

trustpoint/pki/signals.py
trustpoint/pki/tasks.py

- Fixed timezone-naive datetime object
- Fixed heapq exception if two CRLs are scheduled for the same time (tuple comparison tried to compare CA models)
- Fixed CRL being always generated on server start even if not due yet
**Notes** 
Long-term we might want to integrate CRL scheduler into the Task Scheduler used for notifications. I would keep them separate for the beta release however.
**Legal**

Fix CRL scheduler

---

trustpoint/devices/models.py
trustpoint/pki/__init__.py
trustpoint/pki/pki/request/handler/messagehandler/cert_message_handler.py

Parses the device unique name and adds the relation between cmp issued application certs to device.
**Legal**

Save additional infos to certificate

---

trustpoint/onboarding/cli_builder.py

Renamed the command for the client for the onboarding process.
provision -> onboard
**Notes**
We should use the term provision for injecting the IDevID only, but not for the actual onboarding process.
**Legal** 

renamed provision to onboard

---

trustpoint/onboarding/api.py
trustpoint/onboarding/crypto_backend.py
trustpoint/pki/initializer/issuing_ca/key_gen.py
trustpoint/pki/issuing_ca.py
trustpoint/pki/pki/cmp/protection/signature_protection.py
trustpoint/pki/pki/request/handler/messagehandler/cert_message_handler.py
trustpoint/pki/pki/request/handler/rest.py
trustpoint/pki/tests/certificate_builder.py
trustpoint/pki/util/ca.py
trustpoint/pki/util/keys.py
trustpoint/sysconf/models.py
trustpoint/util/protocols/est_remote.py

Fix hardcoded SECP256R1 EC Key for newly issued certificates.
**Legal** 

Fix hardcoded SECP256R1 EC Key for newly issued certificates.

---

trustpoint/users/scheduler.py

Quick fix for the db-lock issue on server startup.
**Notes**
Just a sleep for now and reduced the workers to 1.
This must be properly resolved in the future.
**Legal** 

lock-db-fix (quick hack)

---

.github/workflows/docker-manual.yml
docs/source/conf.py
pyproject.toml
trustpoint/trustpoint/api.py
trustpoint/trustpoint/templates/trustpoint/base.html

Bump the version number to `0.2.0-dev` as 0.1.0 release is complete.
**Notes**
This is only a proposal for the naming. We could also go with `0.2.0-alpha0` or `0.2.0-beta1` or similar.
**Legal**

Bump trustpoint version to 0.2.0-dev

---

trustpoint/pki/models.py

Skips chain traversal for all self-signed certs, not only CAs.
**Legal**

Fix RecursionError when trying to obtain certificate chain of non-CA self-signed certificate

---

trustpoint/devices/models.py
trustpoint/onboarding/views.py

Related to #198
Disallow creation of an onboarding process if the device is already onboarded.
**Notes**
This check may need to be updated to take onboarding to multiple domains into account. It should only allow onboarding to a domain if no LDevID is currently active for that domain (or alternatively, the existing LDevID is revoked).
**Legal**

Prevent re-onboarding of already onboarded device (resolves #198)

---

trustpoint/devices/views.py
trustpoint/home/views.py
trustpoint/pki/views/certificates.py
trustpoint/pki/views/domains.py
trustpoint/pki/views/issuing_cas.py
trustpoint/pki/views/truststores.py
trustpoint/settings/views.py
trustpoint/templates/devices/credentials/certificate_lifecycle_management.html
trustpoint/templates/devices/devices.html
trustpoint/templates/home/notifications-tab.html
trustpoint/templates/pki/certificates/certificates.html
trustpoint/templates/pki/devid_registration/table.html
trustpoint/templates/pki/domains/domain.html
trustpoint/templates/pki/issuing_cas/issuing_cas.html
trustpoint/templates/pki/truststores/truststores.html
trustpoint/templates/settings/logging/logging_files.html
trustpoint/trustpoint/settings.py

add a shared variable for table pagination
fix ruff errors in settings.py
**Notes**
Pagination count can be exposed as a user setting in the future, either in Trustpoint settings or client JS based & included as a GET URL query parameter.
**Legal**

Use common variable for pagination

---

trustpoint/pki/models/extension.py

Fixes parsing of two certificate extensions.
**Notes** 
This allows for the import of the Phoenix Contact Root CA as a Truststore, which previously caused an exception.
Tests adding certificates with all extensions should be added to verify each extension is handled correctly down the line.
**Legal**

Fix certificate CRLDistributionPoint and PolicyInfo parsing

---

trustpoint/pki/management/commands/add_domains_and_devices.py
trustpoint/pki/management/commands/create_multiple_test_issuing_cas.py
trustpoint/pki/util/x509.py

Added 6 different signature suites that will be used for the demo data - issuing ca - creation:
RSA-2048-SHA256
RSA-3072-SHA256
RSA-4092-SHA512
ECC-SECP256R1-SHA256
ECC-SECT283R1-SHA256
ECC-SECT571R1-SHA3-512
**Legal** 

Added 6 different signature suites to be used by the management commands to create demo data

---

.dockerignore
trustpoint/settings/views/logging.py

- exclude local logs from docker build
- Replaces invalid characters with a backslash escape sequence (e.g., \x80) for read_text in settings/views/logging.py
**Legal**

log handling

---

Dockerfile

change to base bookworm image
**Legal**

docker  use debian:bookworm-slim without further python package

---

trustpoint/pki/views/domains.py
trustpoint/pki/views/issuing_cas.py
trustpoint/pki/views/truststores.py

Catch ProtectedError and return a messages.error for Issuing CAs, Domains and Truststores if there are referenced objects and the object cannot be deleted
**Legal** 

Save deletion of Issuing CAs, Truststores and Domains

---

trustpoint/pki/management/commands/add_domains_and_devices.py
trustpoint/pki/management/commands/import_idevid_truststores.py
trustpoint/pki/models/__init__.py

- New script to import Truststores: pki/management/commands/import_idevid_truststores.py
- Added truststore according to onboarding protocol: pki/management/commands/add_domains_and_devices.py
**Legal** 
- [ x] I certify that I have all necessary rights to publish this contribution under the MIT license. I agree to the Trustpoint CLA and have added my name to the AUTHORS.md file.

Added Truststores and IDevID Patterns to demo data generation

---

.gitignore
pyproject.toml
trustpoint/features/R_013_remote_credential_download.feature
trustpoint/features/environment.py
trustpoint/features/steps/r_013_steps.py
uv.lock

Implements all steps for client-server testing of remote credential download
**Notes** 
Had to fight behave in two ways to a) fail on uncaught exceptions and b) to handle scenarios that build upon one another, both of which is not supported by default. If you have a cleaner approach, I'd be happy to know!
**Legal**

Behave complete R_013 steps (Remote Credential Download)

---

.github/workflows/docker-manual.yml

Docker compose build must be used for providing the containers on Dockerhub.
**Legal** 

docker manual compose fix

---

trustpoint/trustpoint/middleware.py

Related to #315
Swap the order of conditions in the if-statement
- that way, in case the user is authenticated, `any()` with the public parts does not have to be evaluated
- more readable
Replace placeholder docstring
**Legal**

Default login: Swap condition order and add docstring

---

trustpoint/devices/tests/test_model_delete.py
trustpoint/pki/tests/conftest.py
trustpoint/pki/tests/test_models/test_domain_model.py
trustpoint/pki/tests/test_models/test_issuing_ca_model.py

Related to #322 
Adds some more tests to ensure model deletion protection constraints work as intended.
**Legal**

Add additional tests for model deletion and relation checking

---

trustpoint/pki/management/commands/reset_db.py

Add `--add` option to reset_db, which adds demo data after reset
Raises an exception if OS can't delete sqlite DB file instead of trying to continue on old DB
**Legal**

reset_db improvements

---

docker/RESET_DB
docker/entrypoint.sh
trustpoint/templates/setup_wizard/generate_tls_server_credential.html

Only resets the database and runs migrations if the `RESET_DB` file is present - afterwards delete it.
This file is part of the container build, so the DB is always reset when re-building the container, but never when just re-starting it.
Fixed typo in wizard
**Notes** 
Use `docker compose up -d` for starting the containers.
Important: DO NOT use `docker compose down` if you intend to keep the DB, as this will remove the containers. On the next start, they will be regenerated including the reset file. Use `docker compose stop` instead.
**Legal**

Only reset database on first container start

---

docker-compose.yml

Related to #330 
Add apache and trustpoint config to volume, so after container restart or new build, we can still access it.
**Legal** 

Store apache config and trustpoint config in volume

---

trustpoint/pki/models/certificate.py
trustpoint/pki/tests/test_models/test_certificate_extensions.py
trustpoint/setup_wizard/views.py

Fixes certificate extension deletion
Move certificate unique constraint to SHA256 fingerprint and change pem content to TextField -> This allows postgres to work with certificates that have a larger PEM content than 2704 bytes
**Notes** 
This allows reverting the TLS server certificate generation in the setup wizard before applying it.
**Legal**

Fix certificate extension deletion and TLS server cert wizard cancel

---

pyproject.toml
uv.lock

Adjust "requires-python" value from "~=3.12" to "==3.12.*" because otherwise, uv is potentially grabbing version 3.13.x instead of staying inside the 3.12.x version range. 
**Notes** 
I also update cryptography from 44.0.1 to 44.0.3.
**Legal**

Adjust python version fix

---

trustpoint/pki/forms.py
trustpoint/pki/views/domains.py
trustpoint/pki/views/issuing_cas.py
trustpoint/pki/views/truststores.py
trustpoint/templates/pki/devid_registration/add.html
trustpoint/templates/setup_wizard/tls_server_credential_apply.html
trustpoint/trustpoint/locale/de/LC_MESSAGES/django.po

- Added success messages to Truststore, Domain, and Issuing CA Create views
- Fixed failure on adding CA when the CA certificate was already in the database, but not as a CA
- Cursor change on Registration pattern creation template
**Notes** 
NOT related to #376, the fix contained in this PR is for a separate issue
**Legal**

Added success messages to PKI model create views

---

.github/workflows/pytest.yml

Now, always runs PR report render.
**Legal** 

always runs PR report render

---

.gitignore
.vscode/extensions.json
.vscode/settings.json
.vscode/trustpoint.code-workspace
docs/source/development/development.rst

Adds a new layer (workspace) to the VS Code configuration.
This allows for user-defined settings overrides (branch-persistent with .gitignore)
**Notes** 
For general project configuration, please place all settings in `.vscode/trustpoint.code-workspace`.
In order for these settings to apply, please open this .code-workspace file in the editor instead of the project folder.
Open to feedback on this. An alternative would be to use just settings.json, .gitignore it and use `git add -f .vs-code/settings.json` when you want to make updates for everyone. Both methods are not perfect.
**Legal**

VS Code settings handling

---

.vscode/extensions.json
.vscode/settings.json
.vscode/trustpoint.code-workspace
pyproject.toml
uv.lock

Fixes the mypy and pytest configuration.
Pytest:
Did not import the correct settings.py.
Mypy:
Missing dependencies due to wrong installation method. -> django-stubs[compatible-mypy] instead of django-stubs, django-stubs-ext, mypy separately.
Did not import the correct settings.py, but instead loaded the settings app, thus falling back to global defaults.
Thus, until now, the django plugin for mypy was loaded but no monkey patching occurred, so type inference with django generic types was not happening...
**Legal** 

mypy and pytest configuration fixes

---

trustpoint/aoki/tests/client.py
trustpoint/pki/forms.py
trustpoint/pki/management/commands/reset_db.py

Related to #375 (review by @BytesWelder )
- In Issuing CA and DevOwnerID import forms, put certificates before private key fields
- Fix a bug in reset_db that would inadvertently delete initial migrations
- Change AOKI client step comments
**Legal**

Credential import form UX improvement

---

docs/source/devices/aoki.rst
trustpoint/aoki/management/commands/aoki_gen_test_certs.py
trustpoint/aoki/tests/client.py
trustpoint/aoki/tests/cmp_client.py
trustpoint/aoki/views.py
trustpoint/pki/models/credential.py

This changes the format the IDevID is referenced in an AOKI DevOwnerID certificate from
`<IDevID_Subj_SN>.dev-owner.<IDevID_x509_SN>.<IDevID_SHA256_Fingerprint>.alt`
to
`dev-owner:<IDevID_Subj_SN>.<IDevID_x509_SN>.<IDevID_SHA256_Fingerprint>`
The reason for this change is that we are using the `UniformResourceIdentifier` (URI) GeneralName type in the DevOwnerID SAN extension (as opposed to the `DNSName` type - which would not be the best fit as the device IDevID reference is not a valid DNS-resolvable hostname)
With this change, the SAN entry is a valid URI since it is no longer missing a scheme - in our case, `dev-owner:`. As it is now clearly no longer a hostname, the `.alt` TLD suffix can also be omitted.
**Legal**

Change AOKI DevOwnerID device reference to a valid URI
