trustpoint/pki/management/commands/add_domains_and_devices.py
Related to #
Adding a new management command for adding devices and domains
**Notes** 
**Legal**
=> Adding a management command to add domains and devices

poetry.lock, pyproject.toml
Update of all dependencies
**Legal**
=> dependency update

trustpoint/pki/templates/pki/domains/details.html
=> domain details bug fix

trustpoint/pki/views/issuing_cas.py, trustpoint/sysconf/apps.py, trustpoint/sysconf/forms.py, trustpoint/sysconf/models.py, trustpoint/sysconf/security/__init__.py, trustpoint/sysconf/security/decorators.py, trustpoint/sysconf/security/manager.py, trustpoint/sysconf/signals.py, trustpoint/sysconf/views.py
Related to #75 
Added mixin for CBV sec settings and
a decorator for function based restrictions
**Notes**
Before merge we should remove the todo in IssuingCaTableView.
I left in there for demo purpose if other may want to see in action before merge.
**Legal**
=> Dev security levels

trustpoint/home/templates/home/counts-panel.html
Related to #102
update the progress bat to show both number in one.
**Notes**
=> udpate progress bar to show 2 colors

trustpoint/pki/models.py
Related to #100 
just changed the str representation of DomainDomain and IssuingCaModel
**Legal**
=> fixes #100

trustpoint/devices/models.py, trustpoint/pki/models.py, trustpoint/pki/templates/pki/domains/config.html, trustpoint/pki/templates/pki/issuing_cas/config.html, trustpoint/pki/views/domains.py, trustpoint/pki/views/issuing_cas.py
Added some actual data from database to the config view
**Legal**
=> Fill domain and issuigCA config view with a bit more live data

trustpoint/pki/management/commands/base_commands.py, trustpoint/pki/management/commands/create_test_issuing_ca.py, trustpoint/users/apps.py, trustpoint/users/management/commands/delete_schedules.py, trustpoint/users/scheduler.py, trustpoint/users/tasks.py
Related to #
Bugfixes in notifications and tasks
**Notes** 
**Legal**
=> Updated notifications and schedules to create notifications

trustpoint/pki/forms.py, trustpoint/pki/models.py, trustpoint/pki/pki/request/__init__.py, trustpoint/pki/pki/request/message/__init__.py, trustpoint/pki/pki/request/message/cmp.py, trustpoint/pki/pki/request/message/est.py, trustpoint/pki/pki/request/message/rest.py, trustpoint/pki/signals.py, trustpoint/pki/tables.py, trustpoint/pki/templates/pki/domains/config.html, trustpoint/pki/templates/pki/domains/protocol_config_form.html, trustpoint/pki/templates/pki/truststores/download.html, trustpoint/pki/urls/pki.py, trustpoint/pki/views/domains.py, trustpoint/static/js/domains.js
Added the possibility to configure protocols in a domain and add truststores to it
**Legal**
=> Dev add truststores and protocols to domain config

docs/source/index.rst, docs/source/quickstart.rst
Added a new doc in docs/source/quickstart.rst 
**Legal**
=> Adding a quickstart guide on how to setup Truspoint with Docker

docs/source/community_support.rst, docs/source/faq.rst, docs/source/index.rst, docs/source/introduction.rst
* FAQ
* Community support
* Intro
**Legal**
=> Adding documentation

.readthedocs.yaml
Just a TODO for switching to poetry for docs build deps. We currently need a requirements.txt in the docs directory.
**Legal** 
=> Read the docs

docs/source/index.rst, docs/source/introduction.rst, docs/source/quickstart.rst, docs/source/usage_guide.rst
added docs/source/usage_guide.rst 
added Users and Scenarios section to docs/source/introduction.rst
deleted TOC from docs/source/quickstart.rst
**Legal**
=> Adding a usage guide which explains the main features of Trustpoint

docs/source/index.rst, docs/source/introduction.rst, docs/source/onboarding.rst, docs/source/quickstart_operate.rst, docs/source/quickstart_setup.rst, docs/source/usage_guide.rst
- Added a Quickstart guide for onboarding a device
- Added a sperate section which explains the different onboarding mechanisms
**Legal**
=> Updated documentation

trustpoint/users/tasks.py
Changed URL to https://trustpoint.readthedocs.io
**Legal** 
=> Changed URL of Trustpoint docu

docs/source/quickstart_setup.rst, docs/source/usage_guide.rst
=> Fixed errors while generating the docs

trustpoint/home/api.py, trustpoint/static/js/dashboard/charts-tab.js, trustpoint/static/js/dashboard/counts-panel.js, trustpoint/static/js/dashboard/dashboard.js
Related to #
**Notes** 
**Legal**
=> Dashboard chart change

trustpoint/devices/__init__.py, trustpoint/devices/api.py, trustpoint/devices/filters.py, trustpoint/devices/forms.py, trustpoint/devices/models.py, trustpoint/devices/tables.py, trustpoint/devices/views.py, trustpoint/home/api.py, trustpoint/onboarding/models.py, trustpoint/onboarding/views.py, trustpoint/pki/forms.py, trustpoint/pki/management/commands/add_domains_and_devices_certs.py, trustpoint/pki/templates/pki/domains/config.html, trustpoint/pki/views/domains.py, trustpoint/users/tasks.py
=> Dev quick fixes for beta

trustpoint/onboarding/api.py, trustpoint/onboarding/cli_builder.py, trustpoint/onboarding/views.py, trustpoint/pki/util/keys.py
- adapt openssl key generation command to match device CA signature suite
- fix truststore download otp / ldevid endpoint authentication
**Legal**
=> Cli onboarding fix

README.md, docs/source/index.rst
we're beta now
**Notes** 
**Legal**
=> Readme beta

docs/source/development.rst, docs/source/index.rst, docs/source/onboarding.rst
- Add page development commands (originally in readme)
- Add zero-touch demo instructions
**Legal**
=> Dev commands in docs

.github/workflows/docker-manual.yml
Related to #
**Notes** 
**Legal**
=> Docker latest tag

trustpoint/onboarding/api.py, trustpoint/onboarding/crypto_backend.py, trustpoint/onboarding/models.py, trustpoint/onboarding/tests.py, trustpoint/onboarding/views.py, trustpoint/pki/util/keys.py
Work in progress - just for alignment and preview purposes
DB based onboarding processes TBD
Linting TBD
**Legal**
=> Onboarding refactoring

Dockerfile, trustpoint/trustpoint/settings.py
DOCKER_CONTAINER flag added in settings.py
**Legal** 
=> DOCKER_CONTAINER flag in settings.py

trustpoint/settings/views.py
Fix that home and devices apps will be included in makemigrations and migrate.
Edit:
I also added the logging error fix in this branch, since i didn't want to create an extra branch for two lines :s
**Legal**
=> Dev fix migrations

.dockerignore, Dockerfile, docker/entrypoint.sh, pyproject.toml, uv.lock
Update docker build to use uv instead of poetry
Reduce translation compilation to de and en locales
**Legal**
=> Update docker build to use uv instead of poetry

trustpoint/home/views.py, trustpoint/pki/models/issuing_ca.py, trustpoint/templates/pki/issuing_cas/issuing_cas.html
Related to #240
This is just an extra PR to merge the fixes from #240 separately from the button changes
**Notes** 
Full #240 with button changes should still be merged, consider most preferred button layout together
**Legal**
=> Dev 240 only fixes

pyproject.toml, trustpoint/home/views.py, trustpoint/pki/models/certificate.py, trustpoint/pki/models/issuing_ca.py, trustpoint/settings/views/security.py, trustpoint/templates/home/charts-tab.html, trustpoint/trustpoint/settings.py
Related to #
**Notes** 
**Legal** 
=> moved behave dep in dev env

pyproject.toml, trustpoint/cmp/urls.py, trustpoint/cmp/views.py, trustpoint/devices/forms.py, trustpoint/devices/issuer.py, trustpoint/devices/models.py, trustpoint/devices/urls.py, trustpoint/devices/views.py, trustpoint/pki/admin.py, trustpoint/pki/forms.py, trustpoint/pki/models/certificate.py, trustpoint/templates/devices/help/no_onboarding/cmp_shared_secret.html, trustpoint/templates/devices/help/onboarding/cmp_idevid.html, trustpoint/templates/devices/help/onboarding/cmp_shared_secret.html, uv.lock
=> Fixes and cmp

docs/source/onboarding.rst, docs/source/usage_guide.rst, trustpoint/pki/management/commands/add_domains_and_devices.py
Updated documentation for version bump
Fixed management command to add domains and devices
**Legal**
=> Fhk update docs

trustpoint/pki/urls.py, trustpoint/pki/views/issuing_cas.py, trustpoint/pki/views/truststores.py, trustpoint/templates/pki/truststores/confirm_delete.html, trustpoint/templates/pki/truststores/truststores.html
- Added (bulk) delete for truststores
- Added (bulk) delta success message for issuing CAs
**Legal**
=> Truststore delete

trustpoint/templates/devices/help/onboarding/cmp_idevid.html, trustpoint/templates/devices/help/onboarding/cmp_shared_secret.html
- Added copy to clipboard functionality to IDevID onboarding
- Fixed visual bug in shared secret onboarding
**Legal**
=> Changed onboarding html template

trustpoint/devices/tests/conftest.py, trustpoint/pki/tests/test_auto_gen_pki.py
`OnboardingProcess.MANUAL` is removed
**Legal**
=> fix failing test cases due to OnboardingProtocol changes

.dockerignore, Dockerfile, docker/apache/trustpoint-apache-https.conf, docker/apache/trustpoint-http-init.conf, docker/entrypoint.sh, trustpoint/trustpoint/wsgi.py
Fixed python version, venv and environment issues with the container builds.
Fixed all path issues.
docker compose build 
will build the current state in your local branch
docker compose build --build-arg BRANCH=[branch]
will build the branch, tag or specific commit (hash)
**Legal** 
=> Docker compose and Apache2 Conf fixes

trustpoint/templates/setup_wizard/initial.html
Deactivated "Import TLS-Server Credential From File" button
**Legal** 
=> Deactivated "Import TLS-Server Credential From File" button

trustpoint/templates/devices/details/sub_details.html
=> Added details to the device details view

trustpoint/devices/issuer.py
Fixes hash-algo support.
**Legal** 
=> fix-hash-algorithm-dep-and-support

.github/workflows/docker-manual.yml, pyproject.toml, trustpoint/templates/trustpoint/base.html, uv.lock
Bumps version to 0.2.0
**Notes** 
This shall be merged only as the last commit before creating the `v0.2.0` tag on main.
**Legal**
=> Bump version to v0.2.0

docs/source/conf.py
Fixes the version in the docs config. 0.1.1 -> 0.2.0
**Legal** 
=> version fix docs

.github/workflows/docker-manual.yml
Another try with docker compose.
**Legal** 
=> docker compose try again

.github/workflows/docker-manual.yml
=> fix another try

.github/workflows/docker-manual.yml, docker-compose.yml
Some changes to the docker manual build.
**Legal** 
=> Docker manual build action

.github/workflows/docker-manual.yml, docker-compose.yml
=> Changed Image Names in Docker Manual Action

.github/workflows/docker-manual.yml
Typo fix in dockerhub push commands
**Legal** 
=> Typo fix in dockerhub push commands

Dockerfile
Every command (e.g. RUN, ENV, COPY etc.) Adds a new image layer. By combining multiple commands we can decrease the image size.
The recommended packages also got removed
**Notes**
By not installing the recommended packages and the reduces image layers the building process was locally 16 seconds faster. which is over 30% :P
**Legal** 
=> Slim Dockerfile

.github/workflows/docker-manual.yml, docs/source/ci_cd.rst, docs/source/development.rst, docs/source/diagrams/component_pipeline.puml, docs/source/diagrams/sequence_pipeline.puml, docs/source/glossary.rst
Adds description of the pipelines to the documentation
**Notes** 
Also renames the dockler pipeline.
**Legal**
=> Documentation

trustpoint/devices/views.py, trustpoint/home/views.py, trustpoint/pki/views/certificates.py, trustpoint/pki/views/domains.py, trustpoint/pki/views/issuing_cas.py, trustpoint/pki/views/truststores.py, trustpoint/settings/views/language.py, trustpoint/settings/views/logging.py, trustpoint/settings/views/security.py, trustpoint/trustpoint/forms.py, trustpoint/trustpoint/middleware.py, trustpoint/trustpoint/settings.py, trustpoint/trustpoint/views/base.py, trustpoint/trustpoint/wsgi.py
Login required by default.
To allow a view to be accessible without login use the following decorator:
from django.contrib.auth.decorators import login_not_required
from django.utils.decorators import method_decorator
@method_decorator(login_not_required, name='dispatch')
**Legal** 
=> login-by-default

docs/source/quickstart_operate.rst, docs/source/quickstart_setup.rst
Related to #
Update docker and docker compose instructions
**Notes** 
**Legal**
=> Docker docs update

trustpoint/devices/views.py
Fix two issues with revocation views
- `DeviceRevocationView` had `DeviceModel` as ListView model instead of `IssuedCredentialModel`
- `DeviceCredentialRevocationView` had a minor issue with the pk kwarg that caused the redirect after submission to fail
**Legal**
=> Fix revocation views

trustpoint/devices/tests/conftest.py, trustpoint/devices/tests/test_credential_download.py, trustpoint/pki/tests/test_models/test_domain_model.py, trustpoint/pki/tests/test_models/test_issuing_ca_model.py
Added tests for domain and issuing ca model
**Notes**
**Legal** 
=> Add tests for issuig_ca and domain model

trustpoint/devices/models.py, trustpoint/pki/views/domains.py, trustpoint/pki/views/issuing_cas.py, trustpoint/templates/pki/domains/issued_certificates.html, trustpoint/templates/pki/issuing_cas/issued_certificates.html
There are still several bugs in the certificate list views for domains and issuing cas which this PR tries to fix.
**Legal** 
=> Domain views fix

trustpoint/templates/devices/credentials/certificate_lifecycle_management.html, trustpoint/templates/devices/help/onboarding/cmp_application_credentials.html, trustpoint/templates/devices/help/onboarding/cmp_shared_secret.html
Some CMP Help fixes.
Some CSS fixes.
**Legal** 
=> CMP, CSS fixes

trustpoint/pki/models/credential.py, trustpoint/pki/models/issuing_ca.py, trustpoint/pki/util/keys.py
Fix CRL generation
**Notes**
Still a draft
**Legal** 
=> Fix CRL generation

trustpoint/pki/management/commands/add_domains_and_devices.py
Domain name change in add_domains_and_devices management command.
**Legal** 
=> domain name change

.github/workflows/ruff.yml
Fixes the ruff pipeline.
**Legal**
=> Fix ruff action.

Dockerfile, pyproject.toml
Related to [#TP-62](https://trustpoint.youtrack.cloud/issue/TP-62/Python-Version-Pinning)
Build WSGI and configure Apache
**Legal** 
=> Build wsgi for python 3.12 and configure apache

pyproject.toml
Update uv version inside pyproject.toml file.
**Legal**
=> Update fixed uv version to latest.

trustpoint/home/management/commands/check_certificate_validity.py, trustpoint/home/management/commands/check_issuing_ca_validity.py, trustpoint/home/views.py
MyPy and Ruff compliance of the home application.
**Legal** 
=> ruff & mypy compliance - home app

mypy.ini, pyproject.toml, trustpoint/cmp/views.py, trustpoint/devices/forms.py, trustpoint/devices/issuer.py, trustpoint/devices/models.py, trustpoint/devices/tests/test_model_delete.py, trustpoint/devices/views.py, trustpoint/pki/models/credential.py, trustpoint/pki/util/keys.py, trustpoint/pki/util/x509.py, uv.lock
Mypy and Ruff compliance.
Two errors left, requires trustpoint.views.base refactoring first.
**Legal** 
=> Mypy ruff compliance devices - done except base views

pyproject.toml, trustpoint/conftest.py, trustpoint/devices/tests/test_forms/__init__.py, trustpoint/devices/tests/test_forms/test_browser_login.py, trustpoint/devices/tests/test_forms/test_create_device_form.py, trustpoint/devices/tests/test_forms/test_credential_download_form.py, trustpoint/devices/tests/test_issuer/__init__.py, trustpoint/devices/tests/test_issuer/test_domain_credential.py, trustpoint/devices/tests/test_issuer/test_opcua_client_credential.py, trustpoint/devices/tests/test_issuer/test_opcua_server_credential.py, trustpoint/devices/tests/test_issuer/test_tls_client_credential.py, trustpoint/devices/tests/test_issuer/test_tls_server_credential.py, trustpoint/devices/tests/test_models/__init__.py, trustpoint/devices/tests/test_models/test_device_model.py, trustpoint/devices/tests/test_models/test_issued_credential.py, trustpoint/devices/tests/test_models/test_remote_device_credential.py, trustpoint/devices/tests/test_revocation/__init__.py, trustpoint/devices/tests/test_revocation/test_device_credential_revocation.py, trustpoint/devices/tests/test_urls/__init__.py, trustpoint/devices/tests/test_urls/test_urls.py, trustpoint/pki/tests/test_models/test_certificate_values.py
Added tests for models.py, forms.py , issuer.py , revocation.py and urls.py
**Legal** 
=> Unittests for the devices app

.github/workflows/sbom.yml
Fix incorrect workflow version
**Legal**
=> Fix incorrect workflow version
